var data = [
	{
		id: 1,
		filepath:'anshikachaudhary.html',
		name: 'Anshika Chaudhary',
		image: '../assets/img/Anshika Chaudhary .JPG',
		tagLine: 'Learn Compete Grow',
		post: 'General Secretary, Games and Sports',
		about: '"Jai hind ka naara hai, Agla point humara hai" .....remembering this tennis match at 2019\'s Inter IIT still gives me goosebumps. This was the first time when I cheered for other than Athletics team. The gold medal that I won didn\'t feel like victory on watching my hardworking peers lose.That is when I felt a sense of belongingness and responsibility towards IITK sports community beyond my team. There is a need for a self-sustaining structure that will continue improving the sports culture over the years. Vote for me, and be a part of ushering in the new era of iitk sports, reimagined.',
		manifesto: 'https://drive.google.com/file/d/1YxnAhKWwCkMUHKHAKsS2TQFto6KImw0-/view?usp=sharing',
		poster: ['../assets/img/Posters/anshika.jpg', '../assets/img/Posters/anshika(2).jpg'],
	},
	{
		id: 2,
		filepath:'anshulsingh.html',
		name: 'Anshul Singh',
		image: '../assets/img/Anshul Singh.jpg',
		tagLine: 'Bring_back_glory',
		post: 'General Secretary, Media and Culture',
		about: 'Hello  readers, I am Anshul singh , currently Dance Club coordinator. I envision the Media and Cultural Council always encouraging people to do better and be better, towards unlocking our hidden potentials   some of my initiatives are 1-monthly e-magazine 2-rap culture inside campus 3- short movie on galaxy',
		manifesto: 'https://drive.google.com/file/d/1QnW11d2POOgqrrXHLapCxgCVcVAKj5zE/view?usp=sharing',
		poster: ['../assets/img/Posters/Anshul.jpg'],
	},
	{
		id: 3,
		filepath:'deepakkumar.html',
		name: 'Deepak Kumar',
		image: '../assets/img/Deepak_photo.jpg',
		tagLine: '#GnS4ALL',
		post: 'General Secretary, Games and Sport',
		about: "We talk about medals, we talk about the glory , let's talk about culture. I am Deepak Kumar, contesting for the post of General Secretary,Games and Sports. Since my first year, I have been  actively involved in sports and I see the culture of games and sports has become limited to only contingent people , where the rest of junta do not relate with the activities going on. Leading Kabaddi team as a captain in Udghosh was my first taste in GnS, after then representing my hall as Sports Secretary and leading the council in present tenure as Associate head, I have got an idea as of what is required to make Games and Sports available for everyone, which in turn in depicted in my manifesto. I would request each and every student out there to vote for the benefit of our culture ,to make sure Gns_4_All becomes a true reality.",
		manifesto: 'https://drive.google.com/file/d/1sBwnD9j1zOdFOEaDptS85NkmuJ46taLw/view?usp=sharing',
		poster: ['../assets/img/Posters/Deepak.jpg', '../assets/img/Posters/Deepak(2).jpg'],
	},
	{
		id: 4,
		filepath:'deepeshgarg.html',
		name: 'Deepesh Garg',
		image: '../assets/img/Deepesh_photo.jpg',
		tagLine: 'Build Back Better',
		post: 'General Secretary, Media and Culture',
		about: 'Culture, Emotions & Art drive the foundation of IITK. Had it been about the technique, we would have been machines, working machines! I found the meaning of art in filmmaking & I am passionately pursuing it as the Coordinator, Film Club.I have honed my management skills and gained composure by taking up responsibilities in several festivals.They helped me develop my composure for the work that I have been doing. I aim to take M&C through a smooth transition to campus while promoting self-sustainability in works, collaborations and ideas, and also improving towards inclusivity and diversity among the clubs.Culture, Emotions & Art drive the foundation of IITK. Had it been about the technique, we would have been machines, working machines! I found the meaning of art in filmmaking & I am passionately pursuing it as the Coordinator, Film Club.I have honed my management skills and gained composure by taking up responsibilities in several festivals.They helped me develop my composure for the work that I have been doing. I aim to take M&C through a smooth transition to campus while promoting self-sustainability in works, collaborations and ideas, and also improving towards inclusivity and diversity among the clubs.',
		manifesto: 'https://drive.google.com/file/d/1v_qehw-Q5t_-S_aCU7fIU0gnxxmH1g8i/view?usp=sharing',
		poster: ['../assets/img/Posters/Deepesh garg.jpg'],
	},
	{
		id: 5,
		filepath:'kartikgupta.html',
		name: 'Kartik Gupta',
		image: '../assets/img/Kartik Gupta.jpg',
		tagLine: 'Konnect with Kartik!',
		post: 'President, Students’ Gymkhana',
		about: "I'm Kartik, 3rd year UG in the Maths department, contesting for President, Students' Gymkhana. My previous responsibilities include Chief Secretary, President's Office, President, Hall of Residence - II & Manager, Alumni Relations, Outreach Cell. I understand that Gymkhana can do a lot more and be a lot more. I know that no single approach is right for every individual, and communication with the student community is the key.",
		manifesto: 'https://drive.google.com/file/d/1gxJ5brJcfI57rOv_Xqp3Sfzl3uA7qz_P/view?usp=sharing',
		poster: ['../assets/img/Posters/Kartik gupta.jpg'],
	},
	{
		id: 6,
		filepath:'khusbukishnani.html',
		name: 'Khusbu Kishnani',
		image: '../assets/img/khushbu kishnani.JPG',
		tagLine: 'Be the Exception!',
		post: 'General Secretary, PG Academics and Career',
		about: 'I am doing MS (R) in Signal Processing , Communication & Networks of Electrical Engineering department. Being a MS student, I can relate to the problems faced by both, PhD students (in research) and MTech students (in placements). Being part of both the worlds, I would have a better perspective on the policies to be made for all PG students at IITK. I currently own a YouTube channel, “The Dream Called IIT”, that guides students towards their IIT dream. Also, before joining IITK, my rich experience in handling key positions like captain of basketball team at the Zonal Level, Senior Under Officer at NCC, Head Girl in school, has polished my leadership and management skills.',
		manifesto: 'https://drive.google.com/file/d/1YOhVGK4VPVEX_2DFakvE2i6qi45eW-ni/view?usp=sharing',
		poster: ['../assets/img/Posters/Khushbu.jpg'],
	},
	{
		id: 7,
		filepath:'shlokapatil.html',
		name: 'Shloka Patil',
		image: '../assets/img/Shloka Patil.jpg',
		tagLine: 'Aspire to Inspire',
		post: 'General Secretary, UG Academics and Career',
		about: "I envision the council to represent student community interests and serve as a steadfast path-forger for students' careers. I firmly believe in working to usher in the way to exploring new opportunities and for the council to become a reliable body to guide and aid students. Since its inception, I have been part of the council and realized the need for a transparent and accountable body that allows each student to be a part of and understand the council’s work. I will strive to ensure the student community's collective upliftment through consistent and harmonious work at AnC.",
		manifesto: 'https://drive.google.com/file/d/15gKDw1HZMe2OTAHbRvQHJAOPydzisIpM/view?usp=sharing',
		poster: ['../assets/img/Posters/Shloka patil.jpg'],
	},
	{
		id: 8,
		filepath:'utkarshgupta.html',
		name: 'Utkarsh Gupta',
		image: '../assets/img/Utkarsh Gupta.png',
		tagLine: 'Return to Normalcy',
		post: 'General Secretary, Science and Technology',
		about: 'My name is Utkarsh Gupta and I am contesting for the post of General Secretary, Science and Technology. I am the Coordinator of Electronics Club and was a member of the InterIIT Techmeet 8.0 contingent. I participated in three events and won one gold and two silver medals. My aim is to reignite the competitive spirit in our council and make IIT Kanpur a force to be reckoned with.',
		manifesto: 'https://drive.google.com/file/d/1bV2fQhhqc_lC12CsoWD1Ce9YMA5t9uRa/view?usp=sharing',
		poster: ['../assets/img/Posters/Utkarsh gupta.jpg'],
	},
	{
		id: 9,
		filepath:'vedantsikka.html',
		name: 'Vedaant Sikka',
		image: '../assets/img/Vedaant_photo.jpg',
		tagLine: '#SikkaforStudents',
		post: "President, Students' Gymkhana",
		about: '“I believe in representing the problems of the students to the administration rather than justify decisions of the administration to the students.” I have been the Convener, CoSHA & Acting President, Students’ Gymkhana, which has enabled me to work in various administrative committees and all halls, especially during the pandemic. My varied domain experience in voicing student issues makes me an ideal candidate to represent the students at an institute level with clarity & impact.',
		manifesto: 'https://drive.google.com/file/d/1T5BiOdyeY99WZ_zqquiavrdDnyKXNRSG/view?usp=sharing',
		poster: ['../assets/img/Posters/Vedant.jpeg', '../assets/img/Posters/Vedant(2).jpg'],
	},
];
export default data;
