var data = [
	{
		id: 1,
		filepath:'somyagupta.html',
		name: 'Somya Gupta',
		image: '../../../assets/img/senators20/Somya Gupta.jpeg',
		tagLine: '#somya_for_senator',
		post: 'Senator Y20',
		about: 'I am Somya Gupta. I am from Delhi and am proud to be a part of the IITK family. I am a responsible and an empathetic team player, skilled in delegacy and communication. I am a confident leader and I believe that I will be able to resolve all the issues faced by the Y20 Junta.',
		manifesto: 'https://drive.google.com/file/d/12G1sTtf7Tq35W55xd8F6GrVqtq8fridC/view?usp=sharing',
		poster: ['../../../assets/img/Posters/Somya .jpg"'],
	},
	{
		id: 2,
		filepath:'shreyaagarwal.html',
		name: 'Shreya Agarwal',
		image: '../../../assets/img/senators20/Shreya Agarwal.jpg',
		tagLine: '#Shreya_for_Y20s',
		post: 'Senator Y20',
		about: 'Hey Y20s! I’m Shreya Agarwal, your fellow batchmate from the department of Electrical Engineering. I have been an active member of the Debate and Discussion Society, the Students’ Opinion Society, the English Literary Society, and have been appointed as volunteer for the E-cell. I was an anchor in the Freshers’20 Showcase, helped in putting the event together. I’m now contesting the elections for BT/BS Y20 senator. My mission is to become a senator who’s as approachable as any other friend, and I strive to provide the best experience us Y20s can have in the online, as well as the later offline semesters. My manifesto highlights the key agendas which would help us all in fostering a home-like environment even in online college. I’m always open to any new suggestions, and feel that a senate’s biggest responsibility is to reach out and be open to feedback. Please support me and help me become YOUR voice' ,
		manifesto: 'https://drive.google.com/file/d/1SPn_mkchu5hawtjkx_Ka6BYgadklPlSB/view?usp=sharing',
		poster: ['../../../assets/img/Posters/shreya.jpg'],
	},
	{
		id: 3,
		filepath:'ishansingh.html',
		name: 'Ishan Singh',
		image: '../../../assets/img/senators20/Ishan Singh.jpg',
		tagLine: '#ishan_singh_for_senator',
		post: 'Senator Y20',
		about: "  Myself Ishan, I'm someone who is mature, candid and has integrity. I'm modest, but hard working and I consistently set firm goals for myself. I believe that only collective efforts lead to positive changes. Hence, we'll together make this happen!",
		manifesto: 'https://drive.google.com/file/d/1-DBVFuhyXrguvHjVUzCEmG7s89rCFReT/view?usp=sharing',
		poster: ['../../../assets/img/Posters/Ishan singh.png'],
	},
	{
		id: 4,
		filepath:'harshitraj.html',
		name: 'Harshit Raj',
		image: '../../../assets/img/senators20/Harshit Raj.jpeg',
		tagLine: '#Harshit_for_senate',
		post: 'Senator Y20',
		about: 'I am Harshit Raj, Y20 CSE. am running for Senator Y20 BT-BS. I have this golden opportunity to represent my batch and become your voice which will be aimed at the betterment of all Y20. I look forward to representing Y20 IITK Junta.',
		manifesto: 'https://drive.google.com/file/d/1r8kC6rLbT2BTajJtlm-a6OrxoO6PE0VB/view?usp=sharing',
		poster: ['../../../assets/img/Posters/harshit raj.jpg'],
	},
	{
		id: 5,
		filepath:'arushkumarrai.html',
		name: 'Arush Kumar Rai.',
		image: '../../../assets/img/senators20/Arush Kumar Rai.jpg',
		tagLine: 'FOR Y20 WITH Y20 BY Y20',
		post: 'Senator Y20',
		about: "My name is Arush Kumar rai.I have been class monitor for 4 years not because i was good in class but because i was having a good leadership quality and i am of a very helping nature( as it is not a good thing to say i use to help because it is a basic quality that everybody should have ,i love playing cricket and love to debates with arguably correct people ,i don't hate anyone i hate hateful thoughts.",
		manifesto: 'https://drive.google.com/file/d/1ZWG1PLVVN_trS_oaWeEV0whO_lHygvE1/view?usp=sharing',
		poster: ['../../../assets/img/Posters/Arush kumar rai.jpg'],
	},
	{
		id: 6,
		filepath:'parteek.html',
		name: 'Parteek',
		image: '../../../assets/img/senators20/Parteek.jpg',
		tagLine: 'Parteek will Speak',
		post: 'Senator Y20',
		about: 'Myself Parteek, a Y20 Candidate aspiring to be the voice of your heart in Senate. Many of you might be knowing me as "info group wala parteek". Yes, I do put a lot my efforts there and I will put even more efforts to raise Y20\'s concerns in Senate and get them resolved. Also, I\'d be able to raise the problems and their seriousness much more effectively as I have been an active member of DebSoc. So yeah, Vote wisely coz "Parteek will speak',
		manifesto: 'https://drive.google.com/file/d/1phbnCVmRTSxfb3EiQbnuwlrZIrfUim5E/view?usp=sharing',
		poster: ['../../../assets/img/Posters/Parteek.png'],
	},
	{
		id: 7,
		filepath:'devbarbhaya.html',
		name: 'Dev Barbhaya',
		image: '../../../assets/img/senators20/Dev Barbhaya.jpg',
		tagLine: '#dev_is_DEVoted',
		post: 'Senator Y20',
		about: "Hello Campus Junta, Dev Barbhaya on this end, aspiring to be your representative in the Students' Senate. I'm the Core Team Member at Vox Populi and have enthusiastically participated in various club activities which include- Dance, Drams, ELS, Fine Arts Club, Students' Opinion Society, Film Club among many others. My aim is to be a People's Leader in true sense, i.e. I\'ll be open to all your problems, queries and suggestions. My sole motto will be to make the life of students at IIT-K as memorable and lively as possible so as to make future leaders of tomorrow who may still feel connected to their roots at IIT.",
		manifesto: 'https://drive.google.com/file/d/1quOYaPNsH3rtF9VlAp29Bj91vNFSC0LS/view?usp=sharing',
		poster: ['../../../assets/img/Posters/DEv.jpg'],
	},
	{
		id: 8,
		filepath:'prashantkumarmishra.html',
		name: 'Prashant Kumar Mishra',
		image: '../../../assets/img/senators20/Prashant Kumar Mishra.jpg',
		tagLine: '#Prashant_for_Progress',
		post: "Senator Y20",
		about: 'Hello everyone. I am Prashant Kumar Mishra, candidate for the post of senator BT-BS Y20. “No voice shall go unheard” is my motto. I have done substantial research on the issues in my manifesto and the very commitment and serious attitude of mine, distinguishes me from others. Please use your vote wisely. #Prashant_for_Progress.',
		manifesto: 'https://drive.google.com/file/d/1uCgWY3uBPmH7G0maYJLZOw0KVIg_Bqnk/view?usp=sharing',
		poster: ['../../../assets/img/Posters/Prashant mishra.jpg'],
	},
    {
        id:9,
		filepath:'aakashtrivedi.html',
        name:'Aakash Trivedi',
        image: '../../../assets/img/senators20/Aakash Trivedi.jpeg',
		tagLine: '#AAKASH FOR SENATOR',
		post: "Senator Y20",
		about:'I am Aakash Om Trivedi. I am contesting for the post of Y20 senator. I am an E-cell volunteer. I have taken part in SOS presentation contest. I aim to raise all concerns of my batchmates in the senate and implement all my manifesto points.',
		manifesto: 'https://drive.google.com/file/d/1tlGvoqfD4juu-y2qdy4QQ4q9CbMs19eo/view?usp=sharing',
		poster: ['../../../assets/img/Posters/Aakash om trivedi.jpg'],
    },
    {
        id:10,
		filepath:'abhisheksangwan.html',
        name:'Abhishek Sangwan',
        image: '../../../assets/img/senators20/Abhishek Sangwan.jpg',
		tagLine: '#voteforabhi , #sangwanforsenator',
		post: "Senator Y20",
		about: 'Abhishek Sangwan is well known for his leadership qualities and interactiveness with peeps. I am generous, having a good decision-making quality. I am hardworking, opportunistic, and  optimistic. I will try to eradicate all the problems of our fellow mates and also solve essential issues regarding student welfare. I will keep my promises made in the manifesto.',
		manifesto: 'https://drive.google.com/file/d/1ljJkK4kQZD5gOJRNYaPiDrI7al6m_zgB/view?usp=sharing',
		poster: ['../../../assets/img/Posters/abhishek sangwan.jpg'],
    },
    {
        id:11,
		filepath:'akshunyavijayvargiya.html',
        name:'Akshunya Vijayvargiya',
        image: '../../../assets/img/senators20/Akshunya Vijayvargiya.jpeg',
		tagLine: '#Akshunya_for_Action',
		post: "Senator Y20",
		about: 'The best thing about me is that I am a good listener. I will listen to all your problems and will try to find out the best possible and feasible solution.',
		manifesto: 'https://drive.google.com/file/d/1LIj1tRNB5NnssCtM-d4cqTNt7EFs53T4/view?usp=sharing',
		poster: ['../../../assets/img/Posters/Akshunya.jpg','../../../assets/img/Posters/Akshunya(2).jpg'],
    },
    {
        id:12,
		filepath:'aniketgautam.html',
        name:'Aniket Gautam',
        image: '../../../assets/img/senators20/Aniket Gautam.jpg',
		tagLine: 'I am kind and fair. vote for me . I care!! #vote for Aniket',
		post: "Senator Y20",
		about: 'I am Aniket Gautam. My belief is that Every person is different in IITK, You are special and you deserve more so I will try my best to get the best of the facilities that our prestigious institute can provide for you. i will also try my best to revivie our campus culture in this online semester.',
		manifesto: 'https://drive.google.com/file/d/1zkdVRj4SXM8R63wudpR0LKo7MUPPWQ_V/view?usp=sharing',
		poster: ['../../../assets/img/Posters/Aniket Gautam.jpg'],
    },
    {
        id:13,
		filepath:'bidyutroy.html',
        name:'Bidyut Roy',
        image: '../../../assets/img/senators20/Bidyut Roy.jpg',
		tagLine: '#iitk ka tempo high hai #bidyut sabka bhai hai',
		post: "Senator Y20",
		about: 'Hi everyone! I am Bidyut Roy, a Y20 fresher here at IIT Kanpur. I am a candidate of BT/BS Y20 Senator and would be pleased to represent the Y20 batch at the Students\' Senate in the upcoming General Election and senate proceedings in year 2021. As you are already aware, the Senate considers all of your problems you may face in your college life and finds solutions to those problems. Being a KOS member and E cell volunteer understanding all of your issues I ensure you to address those problems at Senate to sort out those with a suitable solution keeping in mind the overall welfare of the students as well as the Institute. Thank you. Stay healthy and blessed.',
		manifesto: 'https://drive.google.com/file/d/19uXZdZ5wwvsCVeQTjSbNOg35lcW3eR33/view?usp=sharing',
		poster: ['../../../assets/img/Posters/Bidyut roy.jpg'],
    },
	{
		id:14,
		filepath:'divyanshpatel.html',
		name:'Divyansh Patel',
		image:'../../../assets/img/senators20/divyansh patel.jpg',
		tagLine:'Be the change maker',
		post: 'Senator Y20',
		about: "My self divyansh patel. My vision is to keep the things simple for our students ,so that they can live a Chill life . I have focused on primary needs of students . I don't know I will win or not.but I will definitely make the changes . #be the change maker'",
		manifesto:'https://drive.google.com/file/d/190IszxbQQALA8nXq4B4ntb75M7uWCcqD/view?usp=sharing',
		poster: ['../../../assets/img/Posters/Divyansh patel.jpg']
	},
	{
		id:15,
		filepath:'samarthroday.html',
		name:'Samarth Roday',
		image:'../../../assets/img/senators20/samarth roday.jpg',
		tagLine:'#SAMARTHFORSENATOR',
		post: 'Senator Y20',
		about: "Hello everyone! I am Samarth Roday a Y20 student at IITK from BSBE Department. I am contesting the General Elections this year and a prospective candidate for the BT/BS Y20 Senate position. I am a good observer and listener in my opinion , noticing the problems around me quickly and trying to solve them as soon as possible. I am always interested in all sorts of activities ,specifically in sports and music. I am very approachable person. Hence I think I am deserving candidate who can lead everyone in a better way.",
		manifesto:'https://drive.google.com/file/d/16kD1ezu-3d9tDk3y9-DkDEGHVmKrgj30/view?usp=sharing',
		poster: ['../../../assets/img/Posters/samarth reddy.jpg']
	},
	{
		id:16,
		filepath:'shashwatgupta.html',
		name:'Shashwat Gupta',
		image:'../../../assets/img/senators20/Shashwat Gupta.jpg',
		tagLine:'Shashwat4Change',
		post: 'Senator Y20',
		about: "My vision is to be an active student representative of Y20 and to work in a direction that narrows the divide between Gymkhana and Y20 Community",
		manifesto:'https://drive.google.com/file/d/11wbXADf5TNgpK7okn6DUO3frT2h4WkIV/view?usp=sharing',
		poster: ['../../../assets/img/Posters/Shashwat gupta.jpg']
	},
    {
		id:17,
		filepath:'shubhamkumar.html',
		name:'Shubham Kumar',
		image:'../../../assets/img/senators20/shubham kumar.JPG',
		tagLine:'Hoga har baat me dum... Vote for SHUBHAM',
		post: 'Senator Y20',
		about: "Hi everyone, This is shubham kumar, student of cse dept. Y20. Being an active citizen of our country, i volunteers many social works and active member of ngo 'Anna ahaar'. I am able to handle multiple tasks on a daily basis and always use creative approach to solve problems",
		manifesto:'https://drive.google.com/file/d/1N-jlOxaYU9Jdh03kjJkKyR1a8WKUPfEp/view?usp=sharing',
		poster: ['../../../assets/img/Posters/shubham.jpg']
	},
	{
		id:18,
		filepath:'siddhartha.html',
		name:'Siddhartha',
		image:'../../../assets/img/senators20/Siddhartha.jpg',
		tagLine:'#Sid_for_you',
		post: 'Senator Y20',
		about: " Myself Siddhartha Y20 student in branch of EE. I am contesting for the post of senator . I am a hostler since my secondary education . I was in JNV from 6 to 12. Therefore I had experienced many issues which arises in our academic and other fields. I had served there at many responsible positions like school captain, house captain ,class captain from time to time and loved to resolve issues which arise there. It’s my pleasure to be an honored part of IIT KANPUR community and want to continue my services to resolve issues of students along with my academics . I truly love the family culture of IIT K and want to continue it further with all my friends of IITK . So, I want connect with all my batchmates ,resolve their issues which they are facing now and further issues.",
		manifesto:'https://drive.google.com/file/d/1NR67hAvFx3p0OhObsaUNFhikCWtknHWk/view?usp=sharing',
		poster: ['../../../assets/img/Posters/Siddhartha.jpg']
	},
];

export default data;